"""Upstream ``adcp.signing.errors`` additions, vendored verbatim.

Provenance (see the package docstring for the vendoring rules):

* repo   ``adcontextprotocol/adcp-client-python``, branch ``main``
* PR #987 review follow-up, commit ``fbab8f44`` (merge ``afa04545``) — adds the
  webhook-profile twin of the malformed-target-URI code and its entry in the
  request→webhook code-family translation: ``WEBHOOK_TARGET_URI_MALFORMED`` and the
  ``REQUEST_TARGET_URI_MALFORMED`` row of ``REQUEST_TO_WEBHOOK_CODE``.

Import-path rewrites (the ONLY permitted deviation from upstream bytes):

* every ``REQUEST_SIGNATURE_*`` / ``WEBHOOK_SIGNATURE_*`` constant referenced by the
  mapping is UNCHANGED in 6.6.0 and is imported from the pinned SDK instead of living
  module-locally as upstream has them;
* ``REQUEST_TARGET_URI_MALFORMED`` is imported from the vendored canonical module
  (upstream imports it from its own ``canonical``) — same symbol, same string.

The mapping is copied as upstream's FULL literal rather than patched
(``{**sdk_mapping, new_key: new_value}``) so its bytes — entry order included — stay
diffable against upstream's file. The vendored dict SUPERSEDES the SDK's for every
consumer behind the facade; the 6.6.0 dict differs only by the missing row.
"""

from __future__ import annotations

from adcp.signing.errors import (
    REQUEST_SIGNATURE_AGENT_NOT_IN_BRAND_JSON,
    REQUEST_SIGNATURE_ALG_NOT_ALLOWED,
    REQUEST_SIGNATURE_BRAND_JSON_AMBIGUOUS,
    REQUEST_SIGNATURE_BRAND_JSON_MALFORMED,
    REQUEST_SIGNATURE_BRAND_JSON_UNREACHABLE,
    REQUEST_SIGNATURE_BRAND_JSON_URL_MISSING,
    REQUEST_SIGNATURE_BRAND_ORIGIN_MISMATCH,
    REQUEST_SIGNATURE_CAPABILITIES_UNREACHABLE,
    REQUEST_SIGNATURE_COMPONENTS_INCOMPLETE,
    REQUEST_SIGNATURE_COMPONENTS_UNEXPECTED,
    REQUEST_SIGNATURE_DIGEST_MISMATCH,
    REQUEST_SIGNATURE_HEADER_MALFORMED,
    REQUEST_SIGNATURE_INVALID,
    REQUEST_SIGNATURE_JWKS_UNAVAILABLE,
    REQUEST_SIGNATURE_JWKS_UNTRUSTED,
    REQUEST_SIGNATURE_KEY_ORIGIN_MISMATCH,
    REQUEST_SIGNATURE_KEY_ORIGIN_MISSING,
    REQUEST_SIGNATURE_KEY_PURPOSE_INVALID,
    REQUEST_SIGNATURE_KEY_REVOKED,
    REQUEST_SIGNATURE_KEY_UNKNOWN,
    REQUEST_SIGNATURE_PARAMS_INCOMPLETE,
    REQUEST_SIGNATURE_RATE_ABUSE,
    REQUEST_SIGNATURE_REPLAYED,
    REQUEST_SIGNATURE_REQUIRED,
    REQUEST_SIGNATURE_REVOCATION_STALE,
    REQUEST_SIGNATURE_TAG_INVALID,
    REQUEST_SIGNATURE_WINDOW_INVALID,
    WEBHOOK_SIGNATURE_AGENT_NOT_IN_BRAND_JSON,
    WEBHOOK_SIGNATURE_ALG_NOT_ALLOWED,
    WEBHOOK_SIGNATURE_BRAND_JSON_AMBIGUOUS,
    WEBHOOK_SIGNATURE_BRAND_JSON_MALFORMED,
    WEBHOOK_SIGNATURE_BRAND_JSON_UNREACHABLE,
    WEBHOOK_SIGNATURE_BRAND_JSON_URL_MISSING,
    WEBHOOK_SIGNATURE_BRAND_ORIGIN_MISMATCH,
    WEBHOOK_SIGNATURE_CAPABILITIES_UNREACHABLE,
    WEBHOOK_SIGNATURE_COMPONENTS_INCOMPLETE,
    WEBHOOK_SIGNATURE_COMPONENTS_UNEXPECTED,
    WEBHOOK_SIGNATURE_DIGEST_MISMATCH,
    WEBHOOK_SIGNATURE_HEADER_MALFORMED,
    WEBHOOK_SIGNATURE_INVALID,
    WEBHOOK_SIGNATURE_JWKS_UNAVAILABLE,
    WEBHOOK_SIGNATURE_JWKS_UNTRUSTED,
    WEBHOOK_SIGNATURE_KEY_ORIGIN_MISMATCH,
    WEBHOOK_SIGNATURE_KEY_ORIGIN_MISSING,
    WEBHOOK_SIGNATURE_KEY_PURPOSE_INVALID,
    WEBHOOK_SIGNATURE_KEY_REVOKED,
    WEBHOOK_SIGNATURE_KEY_UNKNOWN,
    WEBHOOK_SIGNATURE_PARAMS_INCOMPLETE,
    WEBHOOK_SIGNATURE_RATE_ABUSE,
    WEBHOOK_SIGNATURE_REPLAYED,
    WEBHOOK_SIGNATURE_REQUIRED,
    WEBHOOK_SIGNATURE_REVOCATION_STALE,
    WEBHOOK_SIGNATURE_TAG_INVALID,
    WEBHOOK_SIGNATURE_WINDOW_INVALID,
)

from src.core.signing_contract._upstream.canonical import REQUEST_TARGET_URI_MALFORMED

# Structural code for a malformed authority on the webhook profile. Named
# without the ``webhook_signature_`` prefix the rest of this family carries
# because the spec names it that way: security.mdx's webhook checklist lists
# ``webhook_target_uri_malformed`` in the error taxonomy and requires it at
# step 10 for a malformed or mismatched authority.
WEBHOOK_TARGET_URI_MALFORMED = "webhook_target_uri_malformed"

# Code-family translation used by the webhook verifier wrapper. The verifier
# pipeline raises request_signature_* codes; the wrapper retags them into
# webhook_signature_* before exposing to callers. Keeps the 300-line verifier
REQUEST_TO_WEBHOOK_CODE = {
    REQUEST_SIGNATURE_REQUIRED: WEBHOOK_SIGNATURE_REQUIRED,
    REQUEST_SIGNATURE_HEADER_MALFORMED: WEBHOOK_SIGNATURE_HEADER_MALFORMED,
    REQUEST_TARGET_URI_MALFORMED: WEBHOOK_TARGET_URI_MALFORMED,
    REQUEST_SIGNATURE_PARAMS_INCOMPLETE: WEBHOOK_SIGNATURE_PARAMS_INCOMPLETE,
    REQUEST_SIGNATURE_TAG_INVALID: WEBHOOK_SIGNATURE_TAG_INVALID,
    REQUEST_SIGNATURE_ALG_NOT_ALLOWED: WEBHOOK_SIGNATURE_ALG_NOT_ALLOWED,
    REQUEST_SIGNATURE_WINDOW_INVALID: WEBHOOK_SIGNATURE_WINDOW_INVALID,
    REQUEST_SIGNATURE_COMPONENTS_INCOMPLETE: WEBHOOK_SIGNATURE_COMPONENTS_INCOMPLETE,
    REQUEST_SIGNATURE_COMPONENTS_UNEXPECTED: WEBHOOK_SIGNATURE_COMPONENTS_UNEXPECTED,
    REQUEST_SIGNATURE_KEY_UNKNOWN: WEBHOOK_SIGNATURE_KEY_UNKNOWN,
    REQUEST_SIGNATURE_KEY_PURPOSE_INVALID: WEBHOOK_SIGNATURE_KEY_PURPOSE_INVALID,
    REQUEST_SIGNATURE_INVALID: WEBHOOK_SIGNATURE_INVALID,
    REQUEST_SIGNATURE_DIGEST_MISMATCH: WEBHOOK_SIGNATURE_DIGEST_MISMATCH,
    REQUEST_SIGNATURE_REPLAYED: WEBHOOK_SIGNATURE_REPLAYED,
    REQUEST_SIGNATURE_KEY_REVOKED: WEBHOOK_SIGNATURE_KEY_REVOKED,
    REQUEST_SIGNATURE_REVOCATION_STALE: WEBHOOK_SIGNATURE_REVOCATION_STALE,
    REQUEST_SIGNATURE_JWKS_UNAVAILABLE: WEBHOOK_SIGNATURE_JWKS_UNAVAILABLE,
    REQUEST_SIGNATURE_JWKS_UNTRUSTED: WEBHOOK_SIGNATURE_JWKS_UNTRUSTED,
    REQUEST_SIGNATURE_RATE_ABUSE: WEBHOOK_SIGNATURE_RATE_ABUSE,
    REQUEST_SIGNATURE_BRAND_JSON_URL_MISSING: WEBHOOK_SIGNATURE_BRAND_JSON_URL_MISSING,
    REQUEST_SIGNATURE_CAPABILITIES_UNREACHABLE: WEBHOOK_SIGNATURE_CAPABILITIES_UNREACHABLE,
    REQUEST_SIGNATURE_BRAND_JSON_UNREACHABLE: WEBHOOK_SIGNATURE_BRAND_JSON_UNREACHABLE,
    REQUEST_SIGNATURE_BRAND_JSON_MALFORMED: WEBHOOK_SIGNATURE_BRAND_JSON_MALFORMED,
    REQUEST_SIGNATURE_BRAND_ORIGIN_MISMATCH: WEBHOOK_SIGNATURE_BRAND_ORIGIN_MISMATCH,
    REQUEST_SIGNATURE_AGENT_NOT_IN_BRAND_JSON: WEBHOOK_SIGNATURE_AGENT_NOT_IN_BRAND_JSON,
    REQUEST_SIGNATURE_BRAND_JSON_AMBIGUOUS: WEBHOOK_SIGNATURE_BRAND_JSON_AMBIGUOUS,
    REQUEST_SIGNATURE_KEY_ORIGIN_MISMATCH: WEBHOOK_SIGNATURE_KEY_ORIGIN_MISMATCH,
    REQUEST_SIGNATURE_KEY_ORIGIN_MISSING: WEBHOOK_SIGNATURE_KEY_ORIGIN_MISSING,
}
