# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_text-asset_json.json
#   source_etag: W/"68f2761a-2b2"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class TextAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["text"]
    content: Annotated[str, Field(description="Text content")]
    max_length: Annotated[int | None, Field(description="Maximum character length constraint", ge=1)] = None
    language: Annotated[str | None, Field(description="Language code (e.g., 'en', 'es', 'fr')")] = None
