# generated by datamodel-codegen:
#   filename:  _schemas_v1_pricing-options_cpcv-option_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class CpcvPricingOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'cpcv_usd_guaranteed')"),
    ]
    pricing_model: Annotated[Literal["cpcv"], Field(description="Cost per completed view (100% completion)")]
    rate: Annotated[float, Field(description="Fixed CPCV rate (cost per 100% completion)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        Optional[float],
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None
