# generated by datamodel-codegen:
#   filename:  _schemas_v1_signals_activate-signal-request_json.json
#   source_etag: W/"68ee6f3c-305"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ActivateSignalRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    signal_agent_segment_id: Annotated[str, Field(description="The universal identifier for the signal to activate")]
    platform: Annotated[str, Field(description="The target platform for activation")]
    account: Annotated[
        str | None, Field(description="Account identifier (required for account-specific activation)")
    ] = None
