# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_brand-manifest-ref_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Optional, Union

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class Logo(BaseModel):
    url: Annotated[AnyUrl, Field(description="URL to the logo asset")]
    tags: Annotated[
        Optional[list[str]],
        Field(
            description="Semantic tags describing the logo variant (e.g., 'dark', 'light', 'square', 'horizontal', 'icon')"
        ),
    ] = None
    width: Annotated[Optional[int], Field(description="Logo width in pixels")] = None
    height: Annotated[Optional[int], Field(description="Logo height in pixels")] = None


class Colors(BaseModel):
    primary: Annotated[
        Optional[str], Field(description="Primary brand color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")
    ] = None
    secondary: Annotated[
        Optional[str], Field(description="Secondary brand color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")
    ] = None
    accent: Annotated[Optional[str], Field(description="Accent color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")] = None
    background: Annotated[
        Optional[str], Field(description="Background color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")
    ] = None
    text: Annotated[Optional[str], Field(description="Text color (hex format)", pattern="^#[0-9A-Fa-f]{6}$")] = None


class Fonts(BaseModel):
    primary: Annotated[Optional[str], Field(description="Primary font family name")] = None
    secondary: Annotated[Optional[str], Field(description="Secondary font family name")] = None
    font_urls: Annotated[Optional[list[AnyUrl]], Field(description="URLs to web font files if using custom fonts")] = (
        None
    )


class AssetType(Enum):
    image = "image"
    video = "video"
    audio = "audio"
    text = "text"


class Asset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_id: Annotated[str, Field(description="Unique identifier for this asset")]
    asset_type: Annotated[AssetType, Field(description="Type of asset")]
    url: Annotated[AnyUrl, Field(description="URL to CDN-hosted asset file")]
    tags: Annotated[
        Optional[list[str]],
        Field(description="Tags for asset discovery (e.g., 'holiday', 'lifestyle', 'product_shot')"),
    ] = None
    name: Annotated[Optional[str], Field(description="Human-readable asset name")] = None
    description: Annotated[Optional[str], Field(description="Asset description or usage notes")] = None
    width: Annotated[Optional[int], Field(description="Image/video width in pixels")] = None
    height: Annotated[Optional[int], Field(description="Image/video height in pixels")] = None
    duration_seconds: Annotated[Optional[float], Field(description="Video/audio duration in seconds")] = None
    file_size_bytes: Annotated[Optional[int], Field(description="File size in bytes")] = None
    format: Annotated[Optional[str], Field(description="File format (e.g., 'jpg', 'mp4', 'mp3')")] = None
    metadata: Annotated[Optional[dict[str, Any]], Field(description="Additional asset-specific metadata")] = None


class FeedFormat(Enum):
    google_merchant_center = "google_merchant_center"
    facebook_catalog = "facebook_catalog"
    custom = "custom"


class UpdateFrequency(Enum):
    realtime = "realtime"
    hourly = "hourly"
    daily = "daily"
    weekly = "weekly"


class ProductCatalog(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feed_url: Annotated[AnyUrl, Field(description="URL to product catalog feed")]
    feed_format: Annotated[Optional[FeedFormat], Field(description="Format of the product feed")] = (
        "google_merchant_center"
    )
    categories: Annotated[
        Optional[list[str]], Field(description="Product categories available in the catalog (for filtering)")
    ] = None
    last_updated: Annotated[Optional[AwareDatetime], Field(description="When the product catalog was last updated")] = (
        None
    )
    update_frequency: Annotated[
        Optional[UpdateFrequency], Field(description="How frequently the product catalog is updated")
    ] = None


class Disclaimer(BaseModel):
    text: Annotated[str, Field(description="Disclaimer text")]
    context: Annotated[
        Optional[str],
        Field(description="When this disclaimer applies (e.g., 'financial_products', 'health_claims', 'all')"),
    ] = None
    required: Annotated[Optional[bool], Field(description="Whether this disclaimer must appear")] = True


class Contact(BaseModel):
    email: Annotated[Optional[EmailStr], Field(description="Contact email")] = None
    phone: Annotated[Optional[str], Field(description="Contact phone number")] = None


class Metadata(BaseModel):
    created_date: Annotated[Optional[AwareDatetime], Field(description="When this brand manifest was created")] = None
    updated_date: Annotated[Optional[AwareDatetime], Field(description="When this brand manifest was last updated")] = (
        None
    )
    version: Annotated[Optional[str], Field(description="Brand card version number")] = None


class BrandManifestReference1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[
        AnyUrl,
        Field(
            description="Primary brand URL for context and asset discovery. Creative agents can infer brand information from this URL."
        ),
    ]
    name: Annotated[Optional[str], Field(description="Brand or business name")] = None
    logos: Annotated[
        Optional[list[Logo]], Field(description="Brand logo assets with semantic tags for different use cases")
    ] = None
    colors: Annotated[Optional[Colors], Field(description="Brand color palette")] = None
    fonts: Annotated[Optional[Fonts], Field(description="Brand typography guidelines")] = None
    tone: Annotated[
        Optional[str],
        Field(
            description="Brand voice and messaging tone (e.g., 'professional', 'casual', 'humorous', 'trustworthy', 'innovative')"
        ),
    ] = None
    tagline: Annotated[Optional[str], Field(description="Brand tagline or slogan")] = None
    assets: Annotated[
        Optional[list[Asset]],
        Field(
            description="Brand asset library with explicit assets and tags. Assets are referenced inline with URLs pointing to CDN-hosted files."
        ),
    ] = None
    product_catalog: Annotated[
        Optional[ProductCatalog],
        Field(
            description="Product catalog information for e-commerce advertisers. Enables SKU-level creative generation and product selection."
        ),
    ] = None
    disclaimers: Annotated[
        Optional[list[Disclaimer]],
        Field(description="Legal disclaimers or required text that must appear in creatives"),
    ] = None
    industry: Annotated[
        Optional[str], Field(description="Industry or vertical (e.g., 'retail', 'automotive', 'finance', 'healthcare')")
    ] = None
    target_audience: Annotated[Optional[str], Field(description="Primary target audience description")] = None
    contact: Annotated[Optional[Contact], Field(description="Brand contact information")] = None
    metadata: Annotated[Optional[Metadata], Field(description="Additional brand metadata")] = None


class Asset1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_id: Annotated[str, Field(description="Unique identifier for this asset")]
    asset_type: Annotated[AssetType, Field(description="Type of asset")]
    url: Annotated[AnyUrl, Field(description="URL to CDN-hosted asset file")]
    tags: Annotated[
        Optional[list[str]],
        Field(description="Tags for asset discovery (e.g., 'holiday', 'lifestyle', 'product_shot')"),
    ] = None
    name: Annotated[Optional[str], Field(description="Human-readable asset name")] = None
    description: Annotated[Optional[str], Field(description="Asset description or usage notes")] = None
    width: Annotated[Optional[int], Field(description="Image/video width in pixels")] = None
    height: Annotated[Optional[int], Field(description="Image/video height in pixels")] = None
    duration_seconds: Annotated[Optional[float], Field(description="Video/audio duration in seconds")] = None
    file_size_bytes: Annotated[Optional[int], Field(description="File size in bytes")] = None
    format: Annotated[Optional[str], Field(description="File format (e.g., 'jpg', 'mp4', 'mp3')")] = None
    metadata: Annotated[Optional[dict[str, Any]], Field(description="Additional asset-specific metadata")] = None


class ProductCatalog1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feed_url: Annotated[AnyUrl, Field(description="URL to product catalog feed")]
    feed_format: Annotated[Optional[FeedFormat], Field(description="Format of the product feed")] = (
        "google_merchant_center"
    )
    categories: Annotated[
        Optional[list[str]], Field(description="Product categories available in the catalog (for filtering)")
    ] = None
    last_updated: Annotated[Optional[AwareDatetime], Field(description="When the product catalog was last updated")] = (
        None
    )
    update_frequency: Annotated[
        Optional[UpdateFrequency], Field(description="How frequently the product catalog is updated")
    ] = None


class BrandManifestReference2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[
        Optional[AnyUrl],
        Field(
            description="Primary brand URL for context and asset discovery. Creative agents can infer brand information from this URL."
        ),
    ] = None
    name: Annotated[str, Field(description="Brand or business name")]
    logos: Annotated[
        Optional[list[Logo]], Field(description="Brand logo assets with semantic tags for different use cases")
    ] = None
    colors: Annotated[Optional[Colors], Field(description="Brand color palette")] = None
    fonts: Annotated[Optional[Fonts], Field(description="Brand typography guidelines")] = None
    tone: Annotated[
        Optional[str],
        Field(
            description="Brand voice and messaging tone (e.g., 'professional', 'casual', 'humorous', 'trustworthy', 'innovative')"
        ),
    ] = None
    tagline: Annotated[Optional[str], Field(description="Brand tagline or slogan")] = None
    assets: Annotated[
        Optional[list[Asset1]],
        Field(
            description="Brand asset library with explicit assets and tags. Assets are referenced inline with URLs pointing to CDN-hosted files."
        ),
    ] = None
    product_catalog: Annotated[
        Optional[ProductCatalog1],
        Field(
            description="Product catalog information for e-commerce advertisers. Enables SKU-level creative generation and product selection."
        ),
    ] = None
    disclaimers: Annotated[
        Optional[list[Disclaimer]],
        Field(description="Legal disclaimers or required text that must appear in creatives"),
    ] = None
    industry: Annotated[
        Optional[str], Field(description="Industry or vertical (e.g., 'retail', 'automotive', 'finance', 'healthcare')")
    ] = None
    target_audience: Annotated[Optional[str], Field(description="Primary target audience description")] = None
    contact: Annotated[Optional[Contact], Field(description="Brand contact information")] = None
    metadata: Annotated[Optional[Metadata], Field(description="Additional brand metadata")] = None


class BrandManifestReference(RootModel[Union[Union[BrandManifestReference1, BrandManifestReference2], AnyUrl]]):
    root: Annotated[
        Union[Union[BrandManifestReference1, BrandManifestReference2], AnyUrl],
        Field(
            description="Brand manifest provided either as an inline object or a URL string pointing to a hosted manifest",
            examples=[
                {
                    "description": "Inline brand manifest",
                    "data": {
                        "url": "https://acmecorp.com",
                        "name": "ACME Corporation",
                        "colors": {"primary": "#FF6B35"},
                    },
                },
                {
                    "description": "URL string reference to hosted manifest",
                    "data": "https://cdn.acmecorp.com/brand-manifest.json",
                },
            ],
            title="Brand Manifest Reference",
        ),
    ]
