# generated by datamodel-codegen:
#   filename:  _schemas_v1_standard-formats_index_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpStandardCreativeFormatsRegistry(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Authoritative registry of standard creative formats for Ad Context Protocol",
            title="AdCP Standard Creative Formats Registry",
        ),
    ]
