# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_update-media-buy-request_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional, Union

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class GeoCountryAnyOfItem(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Z]{2}$")]


class FrequencyCap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    suppress_minutes: Annotated[float, Field(description="Minutes to suppress after impression", ge=0.0)]


class TargetingOverlay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(description="Frequency capping settings for package-level application", title="Frequency Cap"),
    ] = None


class Packages(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[str, Field(description="Publisher's ID of package to update")]
    buyer_ref: Annotated[Optional[str], Field(description="Buyer's reference for the package to update")] = None
    budget: Annotated[
        Optional[float],
        Field(
            description="Updated budget allocation for this package in the currency specified by the pricing option",
            ge=0.0,
        ),
    ] = None
    active: Annotated[Optional[bool], Field(description="Pause/resume specific package")] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_ids: Annotated[Optional[list[str]], Field(description="Update creative assignments")] = None


class TargetingOverlay9(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(description="Frequency capping settings for package-level application", title="Frequency Cap"),
    ] = None


class Packages5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[Optional[str], Field(description="Publisher's ID of package to update")] = None
    buyer_ref: Annotated[str, Field(description="Buyer's reference for the package to update")]
    budget: Annotated[
        Optional[float],
        Field(
            description="Updated budget allocation for this package in the currency specified by the pricing option",
            ge=0.0,
        ),
    ] = None
    active: Annotated[Optional[bool], Field(description="Pause/resume specific package")] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay9],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_ids: Annotated[Optional[list[str]], Field(description="Update creative assignments")] = None


class Scheme(Enum):
    bearer = "Bearer"
    hmac_sha256 = "HMAC-SHA256"


class Authentication(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schemes: Annotated[
        list[Scheme],
        Field(
            description="Array of authentication schemes. Supported: ['Bearer'] for simple token auth, ['HMAC-SHA256'] for signature verification (recommended for production)",
            max_length=1,
            min_length=1,
        ),
    ]
    credentials: Annotated[
        str,
        Field(
            description="Credentials for authentication. For Bearer: token sent in Authorization header. For HMAC-SHA256: shared secret used to generate signature. Minimum 32 characters. Exchanged out-of-band during onboarding.",
            min_length=32,
        ),
    ]


class PushNotificationConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[AnyUrl, Field(description="Webhook endpoint URL for task status notifications")]
    token: Annotated[
        Optional[str],
        Field(
            description="Optional client-provided token for webhook validation. Echoed back in webhook payload to validate request authenticity.",
            min_length=16,
        ),
    ] = None
    authentication: Annotated[
        Authentication, Field(description="Authentication configuration for webhook delivery (A2A-compatible)")
    ]


class UpdateMediaBuyRequest1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_buy_id: Annotated[str, Field(description="Publisher's ID of the media buy to update")]
    buyer_ref: Annotated[Optional[str], Field(description="Buyer's reference for the media buy to update")] = None
    active: Annotated[Optional[bool], Field(description="Pause/resume the entire media buy")] = None
    start_time: Annotated[
        Optional[Union[str, AwareDatetime]],
        Field(description="Campaign start timing: 'asap' or ISO 8601 date-time", title="Start Timing"),
    ] = None
    end_time: Annotated[Optional[AwareDatetime], Field(description="New end date/time in ISO 8601 format")] = None
    budget: Annotated[
        Optional[float],
        Field(
            description="Updated total budget for this media buy. Currency is determined by the pricing_option_id selected in each package.",
            ge=0.0,
        ),
    ] = None
    packages: Annotated[Optional[list[Union[Packages, Packages5]]], Field(description="Package-specific updates")] = (
        None
    )
    push_notification_config: Annotated[
        Optional[PushNotificationConfig],
        Field(
            description="Webhook configuration for asynchronous task notifications. Uses A2A-compatible PushNotificationConfig structure. Supports Bearer tokens (simple) or HMAC signatures (production-recommended).",
            title="Push Notification Config",
        ),
    ] = None


class TargetingOverlay10(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(description="Frequency capping settings for package-level application", title="Frequency Cap"),
    ] = None


class Packages6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[str, Field(description="Publisher's ID of package to update")]
    buyer_ref: Annotated[Optional[str], Field(description="Buyer's reference for the package to update")] = None
    budget: Annotated[
        Optional[float],
        Field(
            description="Updated budget allocation for this package in the currency specified by the pricing option",
            ge=0.0,
        ),
    ] = None
    active: Annotated[Optional[bool], Field(description="Pause/resume specific package")] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay10],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_ids: Annotated[Optional[list[str]], Field(description="Update creative assignments")] = None


class TargetingOverlay11(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(description="Frequency capping settings for package-level application", title="Frequency Cap"),
    ] = None


class Packages7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[Optional[str], Field(description="Publisher's ID of package to update")] = None
    buyer_ref: Annotated[str, Field(description="Buyer's reference for the package to update")]
    budget: Annotated[
        Optional[float],
        Field(
            description="Updated budget allocation for this package in the currency specified by the pricing option",
            ge=0.0,
        ),
    ] = None
    active: Annotated[Optional[bool], Field(description="Pause/resume specific package")] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay11],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_ids: Annotated[Optional[list[str]], Field(description="Update creative assignments")] = None


class Authentication6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schemes: Annotated[
        list[Scheme],
        Field(
            description="Array of authentication schemes. Supported: ['Bearer'] for simple token auth, ['HMAC-SHA256'] for signature verification (recommended for production)",
            max_length=1,
            min_length=1,
        ),
    ]
    credentials: Annotated[
        str,
        Field(
            description="Credentials for authentication. For Bearer: token sent in Authorization header. For HMAC-SHA256: shared secret used to generate signature. Minimum 32 characters. Exchanged out-of-band during onboarding.",
            min_length=32,
        ),
    ]


class PushNotificationConfig3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[AnyUrl, Field(description="Webhook endpoint URL for task status notifications")]
    token: Annotated[
        Optional[str],
        Field(
            description="Optional client-provided token for webhook validation. Echoed back in webhook payload to validate request authenticity.",
            min_length=16,
        ),
    ] = None
    authentication: Annotated[
        Authentication6, Field(description="Authentication configuration for webhook delivery (A2A-compatible)")
    ]


class UpdateMediaBuyRequest2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_buy_id: Annotated[Optional[str], Field(description="Publisher's ID of the media buy to update")] = None
    buyer_ref: Annotated[str, Field(description="Buyer's reference for the media buy to update")]
    active: Annotated[Optional[bool], Field(description="Pause/resume the entire media buy")] = None
    start_time: Annotated[
        Optional[Union[str, AwareDatetime]],
        Field(description="Campaign start timing: 'asap' or ISO 8601 date-time", title="Start Timing"),
    ] = None
    end_time: Annotated[Optional[AwareDatetime], Field(description="New end date/time in ISO 8601 format")] = None
    budget: Annotated[
        Optional[float],
        Field(
            description="Updated total budget for this media buy. Currency is determined by the pricing_option_id selected in each package.",
            ge=0.0,
        ),
    ] = None
    packages: Annotated[Optional[list[Union[Packages6, Packages7]]], Field(description="Package-specific updates")] = (
        None
    )
    push_notification_config: Annotated[
        Optional[PushNotificationConfig3],
        Field(
            description="Webhook configuration for asynchronous task notifications. Uses A2A-compatible PushNotificationConfig structure. Supports Bearer tokens (simple) or HMAC signatures (production-recommended).",
            title="Push Notification Config",
        ),
    ] = None


class UpdateMediaBuyRequest(RootModel[Union[UpdateMediaBuyRequest1, UpdateMediaBuyRequest2]]):
    root: Annotated[
        Union[UpdateMediaBuyRequest1, UpdateMediaBuyRequest2],
        Field(
            description="Request parameters for updating campaign and package settings",
            title="Update Media Buy Request",
        ),
    ]
