# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_javascript-asset_json.json
#   source_etag: W/"68f2761a-26a"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class ModuleType(Enum):
    esm = "esm"
    commonjs = "commonjs"
    script = "script"


class JavascriptAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["javascript"]
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[ModuleType | None, Field(description="JavaScript module type")] = None
