# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_css-asset_json.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class CssAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[str | None, Field(description="CSS media query context (e.g., 'screen', 'print')")] = None
