# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_frequency-cap-scope_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from enum import Enum


class FrequencyCapScope(Enum):
    package = "package"
