# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_sub-asset_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from typing import Annotated, Optional, Union

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class SubAsset1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Annotated[
        str,
        Field(
            description="Type of asset. Common types: headline, body_text, thumbnail_image, product_image, featured_image, logo, cta_text, price_text, sponsor_name, author_name, click_url"
        ),
    ]
    asset_id: Annotated[str, Field(description="Unique identifier for the asset within the creative")]
    content_uri: Annotated[AnyUrl, Field(description="URL for media assets (images, videos, etc.)")]
    content: Annotated[
        Optional[Union[str, list[str]]],
        Field(description="Text content for text-based assets like headlines, body text, CTA text, etc."),
    ] = None


class SubAsset2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Annotated[
        str,
        Field(
            description="Type of asset. Common types: headline, body_text, thumbnail_image, product_image, featured_image, logo, cta_text, price_text, sponsor_name, author_name, click_url"
        ),
    ]
    asset_id: Annotated[str, Field(description="Unique identifier for the asset within the creative")]
    content_uri: Annotated[Optional[AnyUrl], Field(description="URL for media assets (images, videos, etc.)")] = None
    content: Annotated[
        Union[str, list[str]],
        Field(description="Text content for text-based assets like headlines, body text, CTA text, etc."),
    ]


class SubAsset(RootModel[Union[SubAsset1, SubAsset2]]):
    root: Annotated[
        Union[SubAsset1, SubAsset2],
        Field(
            description="Sub-asset for multi-asset creative formats, including carousel images and native ad template variables",
            title="Sub-Asset",
        ),
    ]
