# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_media-buy_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Status(Enum):
    pending_activation = "pending_activation"
    active = "active"
    paused = "paused"
    completed = "completed"


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"


class GeoCountryAnyOfItem(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Z]{2}$")]


class FrequencyCap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    suppress_minutes: Annotated[float, Field(description="Minutes to suppress after impression", ge=0.0)]


class TargetingOverlay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    geo_country_any_of: Annotated[
        Optional[list[GeoCountryAnyOfItem]],
        Field(
            description="Restrict delivery to specific countries (ISO codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_region_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific regions/states. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_metro_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific metro areas (DMA codes). Use for regulatory compliance or RCT testing."
        ),
    ] = None
    geo_postal_code_any_of: Annotated[
        Optional[list[str]],
        Field(
            description="Restrict delivery to specific postal/ZIP codes. Use for regulatory compliance or RCT testing."
        ),
    ] = None
    frequency_cap: Annotated[
        Optional[FrequencyCap],
        Field(description="Frequency capping settings for package-level application", title="Frequency Cap"),
    ] = None


class CreativeAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    weight: Annotated[Optional[float], Field(description="Delivery weight for this creative", ge=0.0, le=100.0)] = None


class FormatIdsToProvideItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_url: Annotated[
        AnyUrl,
        Field(
            description="URL of the agent that defines this format (e.g., 'https://creatives.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats)"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s')",
            pattern="^[a-zA-Z0-9_-]+$",
        ),
    ]


class Status1(Enum):
    draft = "draft"
    active = "active"
    paused = "paused"
    completed = "completed"


class Package(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package_id: Annotated[str, Field(description="Publisher's unique identifier for the package")]
    buyer_ref: Annotated[Optional[str], Field(description="Buyer's reference identifier for this package")] = None
    product_id: Annotated[Optional[str], Field(description="ID of the product this package is based on")] = None
    budget: Annotated[
        Optional[float],
        Field(description="Budget allocation for this package in the currency specified by the pricing option", ge=0.0),
    ] = None
    pacing: Annotated[Optional[Pacing], Field(description="Budget pacing strategy", title="Pacing")] = None
    pricing_option_id: Annotated[
        Optional[str], Field(description="ID of the selected pricing option from the product's pricing_options array")
    ] = None
    bid_price: Annotated[
        Optional[float],
        Field(description="Bid price for auction-based CPM pricing (present if using cpm-auction-option)", ge=0.0),
    ] = None
    impressions: Annotated[Optional[float], Field(description="Impression goal for this package", ge=0.0)] = None
    targeting_overlay: Annotated[
        Optional[TargetingOverlay],
        Field(
            description="Optional geographic refinements for media buys. Most targeting should be expressed in the brief and handled by the publisher. These fields are primarily for geographic restrictions (RCT testing, regulatory compliance).",
            title="Targeting Overlay",
        ),
    ] = None
    creative_assignments: Annotated[
        Optional[list[CreativeAssignment]], Field(description="Creative assets assigned to this package")
    ] = None
    format_ids_to_provide: Annotated[
        Optional[list[FormatIdsToProvideItem]],
        Field(description="Format IDs that creative assets will be provided for this package"),
    ] = None
    status: Annotated[Status1, Field(description="Status of a package", title="Package Status")]


class MediaBuy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_buy_id: Annotated[str, Field(description="Publisher's unique identifier for the media buy")]
    buyer_ref: Annotated[Optional[str], Field(description="Buyer's reference identifier for this media buy")] = None
    status: Annotated[Status, Field(description="Status of a media buy", title="Media Buy Status")]
    promoted_offering: Annotated[str, Field(description="Description of advertiser and what is being promoted")]
    total_budget: Annotated[float, Field(description="Total budget amount", ge=0.0)]
    packages: Annotated[list[Package], Field(description="Array of packages within this media buy")]
    creative_deadline: Annotated[
        Optional[AwareDatetime], Field(description="ISO 8601 timestamp for creative upload deadline")
    ] = None
    created_at: Annotated[Optional[AwareDatetime], Field(description="Creation timestamp")] = None
    updated_at: Annotated[Optional[AwareDatetime], Field(description="Last update timestamp")] = None
