# generated by datamodel-codegen:
#   filename:  _schemas_v1_adagents_json.json
#   source_etag: W/"68f2761a-962"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class AuthorizedAgent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[AnyUrl, Field(description="The authorized agent's API endpoint URL")]
    authorized_for: Annotated[
        str,
        Field(
            description="Human-readable description of what this agent is authorized to sell (e.g., 'Official sales agent for our US and CA display inventory')",
            max_length=500,
            min_length=1,
        ),
    ]


class AuthorizedSalesAgents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        str | None, Field(alias="$schema", description="JSON Schema identifier for this adagents.json file")
    ] = "https://adcontextprotocol.org/schemas/v1/adagents.json"
    authorized_agents: Annotated[
        list[AuthorizedAgent],
        Field(description="Array of sales agents authorized to sell this publisher's inventory", min_length=1),
    ]
    last_updated: Annotated[
        AwareDatetime | None,
        Field(description="ISO 8601 timestamp indicating when this file was last updated (optional but recommended)"),
    ] = None
