# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_snippet-type_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from enum import Enum


class SnippetType(Enum):
    vast_xml = "vast_xml"
    vast_url = "vast_url"
    html = "html"
    javascript = "javascript"
    iframe = "iframe"
    daast_url = "daast_url"
