# generated by datamodel-codegen:
#   filename:  _schemas_v1_pricing-options_cpm-fixed-option_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class CpmFixedRatePricingOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'cpm_usd_guaranteed')"),
    ]
    pricing_model: Annotated[Literal["cpm"], Field(description="Cost per 1,000 impressions")]
    rate: Annotated[float, Field(description="Fixed CPM rate (cost per 1,000 impressions)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        Optional[float],
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None
