# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_creative-assignment_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field


class CreativeAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    creative_id: Annotated[str, Field(description="Unique identifier for the creative")]
    weight: Annotated[Optional[float], Field(description="Delivery weight for this creative", ge=0.0, le=100.0)] = None
