# generated by datamodel-codegen:
#   filename:  _schemas_v1_standard-formats_asset-types_index_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import Field, RootModel


class AdcpAssetTypeDefinitionsRegistry(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Standardized definitions for all asset types used in AdCP creative formats",
            title="AdCP Asset Type Definitions Registry",
        ),
    ]
