# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_css-asset_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class CssAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["css"]
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[Optional[str], Field(description="CSS media query context (e.g., 'screen', 'print')")] = None
