# generated by datamodel-codegen:
#   filename:  _schemas_v1_pricing-options_vcpm-fixed-option_json.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class VcpmFixedRatePricingOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pricing_option_id: Annotated[
        str,
        Field(description="Unique identifier for this pricing option within the product (e.g., 'vcpm_usd_guaranteed')"),
    ]
    pricing_model: Annotated[Literal["vcpm"], Field(description="Cost per 1,000 viewable impressions (MRC standard)")]
    rate: Annotated[float, Field(description="Fixed vCPM rate (cost per 1,000 viewable impressions)", ge=0.0)]
    currency: Annotated[
        str, Field(description="ISO 4217 currency code", examples=["USD", "EUR", "GBP", "JPY"], pattern="^[A-Z]{3}$")
    ]
    min_spend_per_package: Annotated[
        float | None,
        Field(
            description="Minimum spend requirement per package using this pricing option, in the specified currency",
            ge=0.0,
        ),
    ] = None
