# generated by datamodel-codegen:
#   filename:  _schemas_v1_enums_pacing_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from enum import Enum


class Pacing(Enum):
    even = "even"
    asap = "asap"
    front_loaded = "front_loaded"
