# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_javascript-asset_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class ModuleType(Enum):
    esm = "esm"
    commonjs = "commonjs"
    script = "script"


class JavascriptAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["javascript"]
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[Optional[ModuleType], Field(description="JavaScript module type")] = None
