# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_audio-asset_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class AudioAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["audio"]
    url: Annotated[AnyUrl, Field(description="URL to the audio asset")]
    duration_ms: Annotated[Optional[int], Field(description="Audio duration in milliseconds", ge=0)] = None
    format: Annotated[Optional[str], Field(description="Audio file format (mp3, wav, aac, etc.)")] = None
    bitrate_kbps: Annotated[Optional[int], Field(description="Audio bitrate in kilobits per second", ge=1)] = None
