# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_get-media-buy-delivery-request_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class StatusFilter(Enum):
    active = "active"
    pending = "pending"
    paused = "paused"
    completed = "completed"
    failed = "failed"
    all = "all"


class StatusFilterEnum(Enum):
    active = "active"
    pending = "pending"
    paused = "paused"
    completed = "completed"
    failed = "failed"


class GetMediaBuyDeliveryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    media_buy_ids: Annotated[
        Optional[list[str]], Field(description="Array of publisher media buy IDs to get delivery data for")
    ] = None
    buyer_refs: Annotated[
        Optional[list[str]], Field(description="Array of buyer reference IDs to get delivery data for")
    ] = None
    status_filter: Annotated[
        Optional[Union[StatusFilter, list[StatusFilterEnum]]],
        Field(description="Filter by status. Can be a single status or array of statuses"),
    ] = None
    start_date: Annotated[
        Optional[str],
        Field(description="Start date for reporting period (YYYY-MM-DD)", pattern="^\\d{4}-\\d{2}-\\d{2}$"),
    ] = None
    end_date: Annotated[
        Optional[str], Field(description="End date for reporting period (YYYY-MM-DD)", pattern="^\\d{4}-\\d{2}-\\d{2}$")
    ] = None
