# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_start-timing_json.json
#   timestamp: 2025-10-14T00:38:32+00:00

from __future__ import annotations

from typing import Annotated, Union

from pydantic import AwareDatetime, Field, RootModel


class StartTiming(RootModel[Union[str, AwareDatetime]]):
    root: Annotated[
        Union[str, AwareDatetime],
        Field(description="Campaign start timing: 'asap' or ISO 8601 date-time", title="Start Timing"),
    ]
