# generated by datamodel-codegen:
#   filename:  _schemas_v1_media-buy_provide-performance-feedback-response_json.json
#   timestamp: 2025-10-15T12:36:38+00:00

from __future__ import annotations

from typing import Annotated, Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(description="Error code for programmatic handling")]
    message: Annotated[str, Field(description="Human-readable error message")]
    field: Annotated[
        Optional[str], Field(description="Field path associated with the error (e.g., 'packages[0].targeting')")
    ] = None
    suggestion: Annotated[Optional[str], Field(description="Suggested fix for the error")] = None
    retry_after: Annotated[
        Optional[float], Field(description="Seconds to wait before retrying the operation", ge=0.0)
    ] = None
    details: Annotated[Optional[Any], Field(description="Additional task-specific error details")] = None


class ProvidePerformanceFeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    success: Annotated[bool, Field(description="Whether the performance feedback was successfully received")]
    errors: Annotated[
        Optional[list[Error]],
        Field(
            description="Task-specific errors and warnings (e.g., invalid measurement period, missing campaign data)"
        ),
    ] = None
