# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_response_json.json
#   source_etag: W/"68ee6f3c-347"
#   source_last_modified: Tue, 14 Oct 2025 15:41:48 GMT

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ProtocolResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[str, Field(description="Human-readable summary")]
    context_id: Annotated[str | None, Field(description="Session continuity identifier")] = None
    data: Annotated[
        Any | None, Field(description="AdCP task-specific response data (see individual task response schemas)")
    ] = None
