# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_audio-asset_json.json

from __future__ import annotations

from typing import Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class AudioAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[AnyUrl, Field(description="URL to the audio asset")]
    duration_ms: Annotated[int | None, Field(description="Audio duration in milliseconds", ge=0)] = None
    format: Annotated[str | None, Field(description="Audio file format (mp3, wav, aac, etc.)")] = None
    bitrate_kbps: Annotated[int | None, Field(description="Audio bitrate in kilobits per second", ge=1)] = None
