# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_javascript-asset_json.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ModuleType(Enum):
    esm = "esm"
    commonjs = "commonjs"
    script = "script"


class JavascriptAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: Annotated[str, Field(description="JavaScript content")]
    module_type: Annotated[ModuleType | None, Field(description="JavaScript module type")] = None
