# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_promoted-offerings-asset_json.json
#   source_etag: W/"68f2761a-3f6"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Colors(BaseModel):
    primary: str | None = None
    secondary: str | None = None
    accent: str | None = None


class PromotedOfferingsAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["promoted_offerings"]
    url: Annotated[
        AnyUrl | None, Field(description="URL of the advertiser's brand or offering (e.g., https://retailer.com)")
    ] = None
    colors: Annotated[Colors | None, Field(description="Brand colors")] = None
    fonts: Annotated[list[str] | None, Field(description="Brand fonts")] = None
    tone: Annotated[str | None, Field(description="Brand tone/voice")] = None
