# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_url-asset_json.json
#   source_etag: W/"68f2761a-240"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class UrlAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["url"]
    url: Annotated[AnyUrl, Field(description="URL reference")]
    description: Annotated[str | None, Field(description="Description of what this URL points to")] = None
