# generated by datamodel-codegen:
#   filename:  _schemas_v1_core_assets_css-asset_json.json
#   source_etag: W/"68f2761a-235"
#   source_last_modified: Fri, 17 Oct 2025 17:00:10 GMT

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class CssAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asset_type: Literal["css"]
    content: Annotated[str, Field(description="CSS content")]
    media: Annotated[str | None, Field(description="CSS media query context (e.g., 'screen', 'print')")] = None
